spring.application.name=elasticsearch

spring.datasource.url=jdbc:postgresql://ep-damp-art-an6gpnp0-pooler.c-6.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ke8cht5FuyrP

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

elasticsearch.api.key=LXlRSXY1MEJfTHMyMGVXSHFGb186dGdmSnhWcndoZVp4VFI3dUJvMjdPZw==
elasticsearch.url=https://my-elasticsearch-project-ac3a77.es.us-central1.gcp.elastic.cloud:443